# This is a generated file. Not intended for manual editing.
services:
  adly.api:
    build:
      context: "C:\\Projects\\Github Projects\\Adly"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "adly.api:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57400"
    volumes:
    - "C:\\Projects\\Github Projects\\Adly\\src\\Ui\\Adly.Api:/app:rw"
    - "C:\\Projects\\Github Projects\\Adly:/src:rw"
    - "C:\\Users\\User\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\User\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\User\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_12_31_13_02_12:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
